Task 15.5
AdamPawlinski/task-15.5 pull request #1
Opened 2018-05-01 10:43 UTC by AdamPawlinski

task finished. Please accept merging.

2018-05-02 07:31 UTC, matwjablonski requested changes

2018-05-02 07:31 UTC, matwjablonski commented on components/app.js
> +    //   this.setState({
commented code to remove

2018-05-03 04:57 UTC, AdamPawlinski commented
removed

2018-05-03 09:52 UTC, matwjablonski approved these changes

2018-09-17 04:43 UTC, merged